name: Deploy JaCoCo and JavaDoc to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and generate reports
        run: mvn clean verify javadoc:javadoc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site # Adjust to where your reports are generated
          keep_files: true # Set to false if you don't want to keep older files
          publish_branch: gh-pages # Branch to publish to, typically gh-pages
